import arcpy
hosp_csv = r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\_original\hospitals_hcris.csv'
arcpy.CreateFileGDB_management(r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data', input, "CURRENT")
arcpy.CreateFileGDB_management(r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data', "input","CURRENT")
arcpy.TableToTable_conversion(hosp_csv, r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb', hospitals)
 arcpy.TableToTable_conversion(hosp_csv, r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb', "hospitals")
arcpy.TableToTable_conversion(hosp_csv, r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb', "hospitals")
arcpy.TableSelect_analysis(r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb\hospitals', r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb\putnam', !city! = "carmel")
arcpy.TableSelect_analysis(r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb\hospitals', r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb\putnam',"city" = 'CARMEL')
arcpy.TableSec
arcpy.TableSelect_analysis(r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb\hospitals',r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb\hospitals_putnam', "city" = 'CARMEL')
arcpy.TableSelect_analysis("C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals","C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals_TableSelect1",""""city" = 'CARMEL'""" AND """"state" = 'NY'""" )
arcpy.TableSelect_analysis("C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals","C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals_TableSelect1",""""city" = 'CARMEL' AND "state" = 'NY'""" )
arcpy.TableSelect_analysis(r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb\hospitals',r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb\hospitals_putnam', "city" = 'CARMEL')
arcpy.TableSelect_analysis("C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals","C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals_TableSelect1",""""city" = 'CARMEL'""")
arcpy.TableToTable_conversion(hosp_csv, r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb', hospitals)
arcpy.TableToTable_conversion(hosp_csv, r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb', "hospitals")
arcpy.TableSelect_analysis("C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals","C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals_TableSelect1",""""city" = 'CARMEL' AND "state" = 'NY'""" )
arcpy.AddField_management(r'C:\Users\DanielMSheehan\SpiderOak\projects\hospitals\data\input.gdb\hospitals', "uid", "LONG", )
arcpy.CalculateField_management("C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals","uid","!OBJECTID! + 1000000","PYTHON_9.3","#")
arcpy.TableToTable_conversion("C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals","C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb","hospitals_addr","#","""street "street" true true false 255 Text 0 0 ,First,#,C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals,street,-1,-1;city "city" true true false 255 Text 0 0 ,First,#,C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals,city,-1,-1;state "state" true true false 255 Text 0 0 ,First,#,C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals,state,-1,-1;zip "zip" true true false 255 Text 0 0 ,First,#,C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals,zip,-1,-1;county "county" true true false 255 Text 0 0 ,First,#,C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals,county,-1,-1;hospname "hospname" true true false 255 Text 0 0 ,First,#,C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals,hospname,-1,-1;prov_num "prov_num" true true false 4 Long 0 0 ,First,#,C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals,prov_num,-1,-1;urban_rural "urban_rural" true true false 255 Text 0 0 ,First,#,C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals,urban_rural,-1,-1;po_box "po_box" true true false 255 Text 0 0 ,First,#,C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals,po_box,-1,-1;prvdr_ctrl_type_cd "prvdr_ctrl_type_cd" true true false 4 Long 0 0 ,First,#,C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals,prvdr_ctrl_type_cd,-1,-1;prvdr_num "prvdr_num" true true false 4 Long 0 0 ,First,#,C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals,prvdr_num,-1,-1;fyear "fyear" true true false 4 Long 0 0 ,First,#,C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals,fyear,-1,-1;uid "uid" true true false 4 Long 0 0 ,First,#,C:/Users/DanielMSheehan/SpiderOak/projects/hospitals/data/input.gdb/hospitals,uid,-1,-1""","#")

